### ISSUE TITLE
Files not deployed to storage account

### ISSUE THREAD

**Issue by ralphke** [microsoft/ignite-learning-paths-training-data#1]
Within the current deployment script, the data and logfiles are not deployed to the storage containers.
in my deployment the container data and log are empty after a successful deployment.

**Comment by amynic** [comment]
Hi @ralphke It looks like the deployment script creates all infrastructure however at the bottom of this page: https://github.com/microsoft/ignite-learning-paths-training-data/blob/master/data10/deployment/README.md you have instructions to add data files via curl or bash commands - have you completed this step and still you see no files?

**Comment by ilikesql** [comment]
This was fixed

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amynic** [comment]
Thanks @ilikesql - can you confirm what was fixed. I just tested the deploy to Azure template (infrastructure only) and then used cloud shell to copy the files to the storage account - this seems success - is this correct?

**Comment by ilikesql** [comment]
As per the deployment script and manual including the curl script, folders are created and files are created, and you validated all services.
________________________________

**Comment by amynic** [comment]
Ok confirmed and tested. Closing this issue
